-----------------------------------------

DEF title = 'Instance Configurations'
DEF main_table = 'OCI360_INST_CONFIG'

BEGIN
  :sql_text := q'{
SELECT distinct ID, DISPLAY_NAME, TIME_CREATED, COMPARTMENT_ID
FROM   OCI360_INST_CONFIG t1
}';
END;
/
@@&&9a_pre_one.

-----------------------------------------

DEF title = 'Instance Configuration Deferred Fields'
DEF main_table = 'OCI360_INST_CONFIG'

BEGIN
  :sql_text := q'{
SELECT ID, DISPLAY_NAME, TIME_CREATED, COMPARTMENT_ID, DEFERRED_FIELDS
FROM   OCI360_INST_CONFIG t1
WHERE  DEFERRED_FIELDS is not null
}';
END;
/
@@&&9a_pre_one.

-----------------------------------------

DEF title = 'Instance Configuration Details'
DEF main_table = 'OCI360_INST_CONFIG'

BEGIN
  :sql_text := q'{
SELECT distinct
       ID,
       DISPLAY_NAME,
       TIME_CREATED,
       COMPARTMENT_ID,
       INSTANCE_DETAILS$INSTANCE_TYPE,
       INSTANCE_DETAILS$LAUNCH_DETAILS$SHAPE,
       INSTANCE_DETAILS$LAUNCH_DETAILS$METADATA$USER_DATA,
       INSTANCE_DETAILS$LAUNCH_DETAILS$METADATA$SSH_AUTHORIZED_KEYS,
       INSTANCE_DETAILS$LAUNCH_DETAILS$IPXE_SCRIPT,
       INSTANCE_DETAILS$LAUNCH_DETAILS$DEFINED_TAGS,
       INSTANCE_DETAILS$LAUNCH_DETAILS$DISPLAY_NAME,
       INSTANCE_DETAILS$LAUNCH_DETAILS$FREEFORM_TAGS,
       INSTANCE_DETAILS$LAUNCH_DETAILS$COMPARTMENT_ID,
       INSTANCE_DETAILS$LAUNCH_DETAILS$SOURCE_DETAILS$IMAGE_ID,
       INSTANCE_DETAILS$LAUNCH_DETAILS$SOURCE_DETAILS$SOURCE_TYPE,
       INSTANCE_DETAILS$LAUNCH_DETAILS$SOURCE_DETAILS$BOOT_VOLUME_ID,
       INSTANCE_DETAILS$LAUNCH_DETAILS$EXTENDED_METADATA,
       INSTANCE_DETAILS$LAUNCH_DETAILS$AVAILABILITY_DOMAIN,
       INSTANCE_DETAILS$LAUNCH_DETAILS$CREATE_VNIC_DETAILS$SUBNET_ID,
       INSTANCE_DETAILS$LAUNCH_DETAILS$CREATE_VNIC_DETAILS$PRIVATE_IP,
       INSTANCE_DETAILS$LAUNCH_DETAILS$CREATE_VNIC_DETAILS$DISPLAY_NAME,
       INSTANCE_DETAILS$LAUNCH_DETAILS$CREATE_VNIC_DETAILS$HOSTNAME_LABEL,
       INSTANCE_DETAILS$LAUNCH_DETAILS$CREATE_VNIC_DETAILS$ASSIGN_PUBLIC_IP,
       INSTANCE_DETAILS$LAUNCH_DETAILS$CREATE_VNIC_DETAILS$SKIP_SOURCE_DEST_CHECK,
       INSTANCE_DETAILS$SECONDARY_VNICS,
       INSTANCE_DETAILS$BLOCK_VOLUMES$VOLUME_ID,
       INSTANCE_DETAILS$BLOCK_VOLUMES$ATTACH_DETAILS$TYPE,
       INSTANCE_DETAILS$BLOCK_VOLUMES$ATTACH_DETAILS$USE_CHAP,
       INSTANCE_DETAILS$BLOCK_VOLUMES$ATTACH_DETAILS$DISPLAY_NAME,
       INSTANCE_DETAILS$BLOCK_VOLUMES$ATTACH_DETAILS$IS_READ_ONLY,
       INSTANCE_DETAILS$BLOCK_VOLUMES$CREATE_DETAILS$SIZE_IN_GBS,
       INSTANCE_DETAILS$BLOCK_VOLUMES$CREATE_DETAILS$DEFINED_TAGS,
       INSTANCE_DETAILS$BLOCK_VOLUMES$CREATE_DETAILS$DISPLAY_NAME,
       INSTANCE_DETAILS$BLOCK_VOLUMES$CREATE_DETAILS$FREEFORM_TAGS,
       INSTANCE_DETAILS$BLOCK_VOLUMES$CREATE_DETAILS$COMPARTMENT_ID,
       INSTANCE_DETAILS$BLOCK_VOLUMES$CREATE_DETAILS$SOURCE_DETAILS$ID,
       INSTANCE_DETAILS$BLOCK_VOLUMES$CREATE_DETAILS$SOURCE_DETAILS$TYPE,
       INSTANCE_DETAILS$BLOCK_VOLUMES$CREATE_DETAILS$BACKUP_POLICY_ID,
       INSTANCE_DETAILS$BLOCK_VOLUMES$CREATE_DETAILS$AVAILABILITY_DOMAIN
FROM   OCI360_INST_CONFIG t1
}';
END;
/
@@&&9a_pre_one.

-----------------------------------------

DEF title = 'Instance Pools'
DEF main_table = 'OCI360_INST_POOLS'

BEGIN
  :sql_text := q'{
SELECT t1.*
FROM   OCI360_INST_POOLS t1
}';
END;
/
@@&&9a_pre_one.

-----------------------------------------

DEF title = 'Instance Pool Members'
DEF main_table = 'OCI360_INST_POOLS_INSTS'

BEGIN
  :sql_text := q'{
SELECT t1.*
FROM   OCI360_INST_POOLS_INSTS t1
}';
END;
/
@@&&9a_pre_one.

-----------------------------------------